package com.gu.contentapi.client.parser
import org.scalatest.{Matchers, FlatSpec}
import JsonFileLoader._

class FrontsJsonParserTest extends FlatSpec with Matchers {
  // generated by:
  // http://content.guardianapis.com/tags.json
  //   ?page-size=2&format=json
  lazy val frontsResponse = JsonParser.parseFronts(loadFile("fronts.json"))

  "fronts endpoint parser" should "parse basic reponse header" in {
    frontsResponse.status should be ("ok")
    frontsResponse.userTier should be ("deprecated")
  }

  it should "parse the fronts" in {
    frontsResponse.results.size should be (3)
    frontsResponse.results.head.title should be ("Sport")
    frontsResponse.results.head.collections.size should be (3)
    frontsResponse.results.head.collections.head should be ("http://content.code.dev-guardianapis.com/collections/uk-sport-regular-stories")
  }
}
